spring.application.name=fooddel

spring.datasource.url=jdbc:postgresql://localhost:5432/fooddel
spring.datasource.username=fooddel_user
spring.datasource.password=FoodDelSecure2026!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=raaviv92@gmail.com
spring.mail.password=slob gqpe aurc niqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
